### ISSUE TITLE
Property "defaultOptions" was accessed during render but is not defined on instance. 

### ISSUE THREAD

**Issue by sstottelaar** [imagekit-developer/imagekit-vuejs#113]
After implementing the IKImage component, I get this warning in the console:

Vue warn: Property "defaultOptions" was accessed during render but is not defined on instance. at <IkImage class="w-full h-full object-fit" path="products/tonke-dragt-als-de-sterren-zingen/9789025873745.jpg" url-endpoint=

Any idea how to fix this?

**Comment by imagekitio** [comment]
Fixed in 3.0.1
