### ISSUE TITLE
Bump imagekit-javascript dependency to 1.3.5

### ISSUE THREAD

**Issue by imagekitio** [imagekit-developer/imagekit-vuejs#16]
The right parameter name for the border is `b` as per [the docs](https://docs.imagekit.io/features/image-transformations/resize-crop-and-other-transformations#border-b)

But the SDK is using `bo`

Bumping the `imagekit-javascript` dependency to version `1.3.5` will solve this issue.

This project's readme.md also needs to be updated to reflect the right values - https://github.com/imagekit-developer/imagekit-vuejs#list-of-supported-transformations

**Comment by logesr** [comment]
I can take this up

**Comment by nick2496** [comment]
Hi, I would like to work on it

**Comment by vibalijoshi** [comment]
Is this still open?

**Comment by imagekitio** [comment]
@vibalijoshi No this has been done, just pending a release. You can have a look at this one - https://github.com/imagekit-developer/imagekit-react/issues/18
