### ISSUE TITLE
TypeError: Cannot read property 'disconnect' of null

### ISSUE THREAD

**Issue by vipr0** [imagekit-developer/imagekit-vuejs#21]
I`m using IKImage component in my Nuxt project. After routing to another page I always get an error "TypeError: Cannot read property 'disconnect' of null". Probably the problem is inside destoyed() method after running this.observer.disconnect()

**Comment by imagekitio** [comment]
Thanks @vipr0 , we will soon release a fix.

**Comment by imagekitio** [comment]
Version 1.0.9 released with the fix.
