### ISSUE TITLE
[Vue, Vue-router]- Error in destroyed hook: "TypeError: this.observer is null"

### ISSUE THREAD

**Issue by shonymon** [imagekit-developer/imagekit-vuejs#23]
Every time i move to another route in app, i get this warnings:

[Vue warn]: Error in destroyed hook: "TypeError: this.observer is null"

found in

---> <IkImage>
       <Navbar> at resources/js/users/modules/chat/navbar.vue
         <Index> at resources/js/users/modules/chat/index.vue
           <Base> at resources/js/users/modules/chat/base.vue
             <Baseapp> at resources/js/users/components/baseapp.vue
               <Root>

**Comment by shonymon** [comment]
solved by adding: 

` destroyed() {
    this.observer.disconnect();
    if(this.observer) {
      this.observer.disconnect();
    }`

on  src/components/IKImage.vue

**Comment by imagekitio** [comment]
Thanks @shonymon, we will soon release a fix.

**Comment by imagekitio** [comment]
Version 1.0.9 released with the fix.

**Comment by imagekitio** [comment]
Version 1.0.9 released with the fix.
