### ISSUE TITLE
Art direction & picture tag

### ISSUE THREAD

**Issue by kbrosseau** [imagekit-developer/imagekit-vuejs#24]
Hello,

Is there any way to reproduce picture & source for art direction via this plugin ? 
And what about srcset? Wich was supported by the non official plugin https://github.com/guastallaigor/vue-image-kit#readme

Thank you

**Comment by imagekitio** [comment]
Vue.js plugin does not calculate values of `srcset` or `sizes` at the moment.

However, you can pass any prop and it will be added as an attribute. We have published a detailed guide on implementing responsive images - https://imagekit.io/responsive-images/

Srcset & sizes - https://imagekit.io/responsive-images/#chapter-5---srcset-with-sizes
Picture element - https://imagekit.io/responsive-images/#chapter-6---using-picture-element
