### ISSUE TITLE
Incompatibility with Nuxt-i18n

### ISSUE THREAD

**Issue by kbrosseau** [imagekit-developer/imagekit-vuejs#25]
Hello,

I have an issue. I run an Nuxt site with i18n plugin. When I install vue-imagekit, I have an error when I switch language : 

client.js?06a0:97 TypeError: Cannot read property 'disconnect' of null
    at VueComponent.destroyed (imagekitio-vue.common.js?000a:500)

Install vue-imagekit cause also a reload when language switch. With is not the correct behavior expected.

Could you help us?

Thank you,
Kevin

**Comment by imagekitio** [comment]
@kbrosseau, I am expecting that your URL changes when you switch the language. If this is the case, then this issue is similar to the other two issues and we will soon release a fix.

**Comment by imagekitio** [comment]
Version 1.0.9 released with the fix.
