### ISSUE TITLE
How to import individual components in NuxtJS?

### ISSUE THREAD

**Issue by dosstx** [imagekit-developer/imagekit-vuejs#32]
I am using NuxtJS (Vue framework) and for some reason I can't destructure the Imagekit SDK like so:

```
import { IKImage, IKContext, IKUpload } from "imagekitio-vue"

export default {
  components: {
    IKImage,
    IKContext,
    IKUpload
  }
}
```

Doing it the above way gives me the following error in console:

```
vue.runtime.esm.js?2b0e:619 [Vue warn]: Unknown custom element: <ik-image> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <Pages/photos/index.vue> at pages/photos/index.vue
       <Nuxt>
         <Layouts/default.vue> at layouts/default.vue
           <Root>
           ```

Anyone got any tips? I have a detailed stackoverflow post here:

https://stackoverflow.com/questions/65391763/imagekit-sdk-and-nuxtjs-how-to-import-sdk-correctly

**Comment by lextract** [comment]
> I am using NuxtJS (Vue framework) and for some reason I can't destructure the Imagekit SDK like so:
> 
> ```
> import { IKImage, IKContext, IKUpload } from "imagekitio-vue"
> 
> export default {
>   components: {
>     IKImage,
>     IKContext,
>     IKUpload
>   }
> }
> ```
> 
> Doing it the above way gives me the following error in console:
> 
> ```
> vue.runtime.esm.js?2b0e:619 [Vue warn]: Unknown custom element: <ik-image> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
> 
> found in
> 
> ---> <Pages/photos/index.vue> at pages/photos/index.vue
>        <Nuxt>
>          <Layouts/default.vue> at layouts/default.vue
>            <Root>
>            ```
> 
> Anyone got any tips? I have a detailed stackoverflow post here:
> 
> https://stackoverflow.com/questions/65391763/imagekit-sdk-and-nuxtjs-how-to-import-sdk-correctly
> ```

Hi dosstx, hope you are well.
Did you overcome this issue? Were you able to use `<ik-image>` component?

**Comment by imagekitio** [comment]
Instead of `ik-image`, use `IKImage`. The answer from Vaibhav Bansal is correct - https://stackoverflow.com/questions/65391763/imagekit-sdk-and-nuxtjs-how-to-import-sdk-correctly
