### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by brunosmm** [imagekit-developer/imagekit-vuejs#33]
Hello,

Would like to know if the IK team will add Typescript support in this component?

Cheers

**Comment by imagekitio** [comment]
Contributions are welcome :) 

We won't be adding it in the next few months.

**Comment by brunosmm** [comment]
I am not using the lib anymore, but sent a contribution to the JS lib:

https://github.com/imagekit-developer/imagekit-javascript/issues/26

**Comment by ankur-dwivedi** [comment]
Utilize [version 2.0.1](https://www.npmjs.com/package/imagekitio-vue/v/2.0.1), which is compatible with Vue 3 and works fine with typescript.

**Comment by mihail727** [comment]
Vue 3, Typescript, Vite.

`yarn add imagekitio-vue` => `The "imagekitio-vue" module declaration file could not be found.`

I may have set something wrong, but Typescript can't detect the types.
