### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by WangHansen** [imagekit-developer/imagekit-vuejs#34]
Hi, just curious if there will be support for vue 3? It doesn't seem to work currently with vite/vue 3 setup

**Comment by imagekitio** [comment]
There are some breaking changes in the global API usage. We are waiting for a dedicated Migration Build of Vue 3 with Vue 2.

**From the migration docs**:
We are still working on a dedicated Migration Build of Vue 3 with Vue 2 compatible behavior and runtime warnings of incompatible usage. If you are planning to migrate a non-trivial Vue 2 app, we strongly recommend waiting for the Migration Build for a smoother experience.

**Comment by kristjanjansen** [comment]
FTY the compatibilty build is now available https://www.npmjs.com/package/@vue/compat

**Comment by brandiqa** [comment]
Adding my voice as well. Hope Vue 3 support gets priority

**Comment by dosstx** [comment]
Check out https://image.nuxtjs.org/providers/imagekit

**Comment by anibalsanchez** [comment]
Same issue here. We are starting a project on Vue 3, but imagekit-vuejs is on Vue.

PS: Take into account that Vue 2 is reaching EOL around April 2022 (Sept 2020 + 18mo).

**Comment by multiplehats** [comment]
Where is Vue 3 support?

**Comment by mlilback** [comment]
I've written my own Vue 3 component for displaying images in a Quasar app. It should provide guidance for anyone else who needs to use ImageKit.io with Vue 3. Written in TypeScript.

Check out [this gist](https://gist.github.com/mlilback/ccd1f104c457b3776b94f1829a6968f6).

**Comment by imagekitio** [comment]
Before March 2023 we shall release support for Vue 3

**Comment by braincomb** [comment]
Was looking into an image provider and IK was looking like a great candidate, but unfortunately we had to pass due to lack of Vue 3 support. Will keep in mind for next projects.

**Comment by mog28** [comment]
> Before March 2023 we shall release support for Vue 3

hi guys, any update on the release?

**Comment by imagekitio** [comment]
Its work in progress - https://github.com/imagekit-developer/imagekit-vuejs/pull/63. Should be released soon.

**Comment by voutchko** [comment]
How soon is soon?

**Comment by zekid26** [comment]
We definitely need this update xD

**Comment by ankur-dwivedi** [comment]
Utilize [version 2.0.1](https://www.npmjs.com/package/imagekitio-vue/v/2.0.1), which is compatible with Vue 3.
