### ISSUE TITLE
eager-loading: convenience method for generating query parameters?

### ISSUE THREAD

**Issue by songololo** [imagekit-developer/imagekit-vuejs#35]
Would it be possible to provide some sort of convenience method for generating the URL for pre-fetching an image?

In a dynamic situation, e.g. carousels, it would be nice to pre-fetch the next image. At the moment, this is possible by creating an additional `ik-image` component and setting the size to 0 or visibility to hidden so that it loads the image in the background.

However, it would be nicer to be able to fetch the next image programmatically, but this involves manually building the query and getting it exactly right so that it matches the query generated by the `ik-image` component.

Thanks.

**Comment by imagekitio** [comment]
You can import `IKCore` like
```
import IKCore from "imagekitio-vue"
```

`IKCore` is essentially our [Javascript SDK](https://github.com/imagekit-developer/imagekit-javascript). You can create an image URL as per the examples shared here - https://github.com/imagekit-developer/imagekit-javascript#url-generation

**Comment by songololo** [comment]
Thanks. This will work.

A request: would it be possible to expose the same logic to the Vue API directly (otherwise it means importing multiple SDKs and figuring out a logic for using the JS version from various components etc.)

**Comment by songololo** [comment]
After a bit of experimentation this seems to work:

1. Import directly from `imagekit-javascript` into the Vue component and initialise.
```js
import ImageKit from 'imagekit-javascript'

// for generating image URLs programmatically
const imageKit = new ImageKit({
  urlEndpoint: 'https://ik.imagekit.io/spokesandneedles/',
})
```
2. Add a Vue `ref` to the html so that the imageKit component can be referenced.
3. Build the URL, using the `ref` to set the correct SDK version in the request parameters
```js
let imgUrl = imageKit.url({
    path: 'some/image/path',
    sdkVersion: this.$refs.<the-ref-name>.IkClient.options.sdkVersion,
    transformation: [/* transformations */]
})
```

It would be handy to have this functionality build directly into the `imagekit-vuejs` component.

Thanks.

**Comment by songololo** [comment]
After a bit of experimentation this seems to work:

1. Import directly from `imagekit-javascript` into the Vue component and initialise.
```js
import ImageKit from 'imagekit-javascript'

// for generating image URLs programmatically
const imageKit = new ImageKit({
  urlEndpoint: 'some/url/path',
})
```
2. Add a Vue `ref` to the html so that the imageKit component can be referenced.
3. Build the URL, using the `ref` to set the correct SDK version in the request parameters
```js
let imgUrl = imageKit.url({
    path: 'some/image/path',
    sdkVersion: this.$refs.<the-ref-name>.IkClient.options.sdkVersion,
    transformation: [/* transformations */]
})
```

It would be handy to have this functionality build directly into the `imagekit-vuejs` component.

Thanks.
