### ISSUE TITLE
lqip parameter doesn't seem to work as intended?

### ISSUE THREAD

**Issue by songololo** [imagekit-developer/imagekit-vuejs#36]
When providing the `lqip` parameter the blurred placeholder image is loaded, but the source image never takes its place.

Is there a trick to using this?

Thanks.

**Comment by imagekitio** [comment]
Are you setting `loading="lazy"` well? In that case, the original image is loaded only when a user scrolls near that section. Otherwise, the original image should start downloading right away, which you can verify from the network calls. If not, please share the minimum code required to reproduce the problem.

**Comment by spocock** [comment]
I've seen similar issue when using `lqip` with `loading="lazy"` when there is more than one image to load. 

I can see in the Network tab it is downloading first the blurred versions and then it downloads a second copy but the second copy is only the source image for the first image, the second image is downloaded again as a blurred image.

This results in the first image showing the source image and the second image getting "stuck" on the blurred image.

![image](https://user-images.githubusercontent.com/5611917/115905284-c9d49c80-a45d-11eb-9d5c-b1cc76744ea5.png)

![image](https://user-images.githubusercontent.com/5611917/115905908-b6760100-a45e-11eb-8762-e91a8acacb3b.png)

The Urls being requested are (XXXXXXXXX my inserts) below. The 4th request is a blurred image not source image.

````
https://ik.imagekit.io/XXXXXXXXXXX/D550_42XXXXXXXXXXXXXXXX.jpg?ik-sdk-version=vuejs-1.0.9&tr=h-256%2Cw-512%3Aq-20%2Cbl-6
https://ik.imagekit.io/XXXXXXXXXXX/201509XXXXXXXXXXXXXXXXX.jpg?ik-sdk-version=vuejs-1.0.9&tr=h-256%2Cw-512%3Aq-20%2Cbl-6%3Aq-20%2Cbl-6
https://ik.imagekit.io/XXXXXXXXXXX/D550_42XXXXXXXXXXXXXXXX.jpg?ik-sdk-version=vuejs-1.0.9&tr=h-256%2Cw-512
https://ik.imagekit.io/XXXXXXXXXXX/201509XXXXXXXXXXXXXXXXX.jpg?ik-sdk-version=vuejs-1.0.9&tr=h-256%2Cw-512%3Aq-20%2Cbl-6
````

Environment:

VueJS/NUXT SSR with the following in a loop accessing an array of source `url`

Images are hosted in the image kit media library

````
                  <client-only>
                    <ik-image
                      :src="url"
                      loading="lazy"
                      :lqip="{active:true}"
                      class="w-full h-48 md:h-64"
                    />
                  </client-only>
````

**Comment by songololo** [comment]
This would explain why it wouldn't work in my case as I was using multiple images. Thanks.

**Comment by imagekitio** [comment]
@songololo @spocock Thanks for sharing this information. We will have a look at this again and will get back if there is any question.

**Comment by vaibhavbansal23** [comment]
Hello @spocock, I created a new nuxt ssr project with default values, installed `imagekitio-vue` package and served three images using a loop with `src`, `loading` and `lqip` parameter as you mentioned and it worked fine for me i.e. first the image was loaded with q-20 and bl-6 and then was replaced with original image on intersection. Here is the sandbox - https://codesandbox.io/s/test-imagekit-vue-nuxt-ssr-gdtmn

Are you sure you are using the correct URLs in `src` param as I can see in the links you provided, the second image has two q-20 and bl-6 and in 4th link one was removed.

**Comment by spocock** [comment]
Hi @vaibhavbansal23 

Thanks for looking into this. I can see it working in your codesandbox.

In this example it just so happened I used the same image twice. See screenshot below.

- (1) when the page loads - both are loaded with q-20 and bl-6 applied, though the 2nd one has that specified twice as you noted. I'm not sure why.  I have no reference in my code to those. They seem to be coming from the library.
- (2) as I scroll down and the two images come into view (they come into view at the same time as they are side by side) they are both loaded again with q-20 and bl-6, and then as the original image, but the second one is not displayed as the full image. Does the order in the timeline looks unexpected, with the q-20,bl-6 one requested last?

  - image with q-20,bl-6
  - full image
  - full image
  - image with q-20,bl-6

> Are you sure you are using the correct URLs in src param as I can see in the links you provided, the second image has two q-20 and bl-6 and in 4th link one was removed.

The `src` image URL I am using for each is displayed above the image. I am using 'raw' URLs and not adding any parameters. The q-20 and bl-6 seem to be being added by the ImageKit library. 

I'm afraid I dont have time to create a full reproduction right now but let me know if there is any other info which may be useful?
Basic code is:

```
  <div v-for="story in filteredNews" :key="story.slug">
          <div class="w-full flex flex-col">
            <div class="">
              <div class="">
                {{ story.title }}
              </div>
                <div class="small">image url: {{story.images[0].url}}</div>
                <client-only>
                  <ik-image
                    :src="story.images[0].url"
                    loading="lazy"
                    :lqip="{active:true}"
                    :transformation="thumbTransform"
                    class="w-full h-48 md:h-64 object-cover"
                  />
                </client-only>
            </div>
        </div>
     </div>
```

![screenshot12](https://user-images.githubusercontent.com/5611917/128895215-c2bd5d20-ef59-4e80-a411-b00a88cb01a9.jpg)

**Comment by imagekitio** [comment]
Closing this issue for now. Feel free to open it again, but please provide minimum reproducible code so that we can provide a fix.
