### ISSUE TITLE
How to use "ik-seo" parameter with this SDK?

### ISSUE THREAD

**Issue by dosstx** [imagekit-developer/imagekit-vuejs#37]
I recently saw this: https://docs.imagekit.io/features/dynamic-seo-suffix

Looks like a good feature. Is it possible to add this to the VueJS SDK?

**Comment by imagekitio** [comment]
You can pass `https://ik.imagekit.io/your_imagekit_id/ik-seo` in the `urlEndpoint` either globally or in the individual `<ik-image` tag as [described in the docs](https://github.com/imagekit-developer/imagekit-vuejs#overriding-urlendpoint-for-a-particular-image).

For example, the following
```
<ik-image 
  path="/default-image.jpg"
  :transformation="[{height:300,width:400}]"
/>
```
becomes
```
<ik-image 
  path="/default-image/seo-friendly-file-name.jpg"
  :transformation="[{height:300,width:400}]"
  urlEndpoint="https://ik.imagekit.io/your_imagekit_id/ik-seo"
/>
```
