### ISSUE TITLE
Error: "Missing urlEndpoint during SDK initialization" when trying to use file upload

### ISSUE THREAD

**Issue by dosstx** [imagekit-developer/imagekit-vuejs#41]
Hello, 
 I am trying to use this package but when I use the below code in my app, I get the following console error:

```
{message: 'Missing urlEndpoint during SDK initialization', help: ''}
```
I did follow the steps on this page to create the required signature based authentication: https://docs.imagekit.io/api-reference/upload-file-api/client-side-file-upload

You can confirm it works here: https://us-central1-pixstery3-50aa9.cloudfunctions.net/setSignatureImageKit

I applied that endpoint to my app like so:

```
<template>
  <div class="sample-app">
    <p>Upload</p>
    <IKContext
      :public-key="publicKey"
      :url-endpoint="urlEndpoint"
      :authentication-endpoint="authenticationEndpoint"
    >
      <IKUpload
        file-name="abc.jpg"
        :tags="['tag1']"
        :response-fields="['tags']"
      />
    </IKContext>
    <p>To use this funtionality please remember to setup the server</p>
  </div>
</template>

<script>
import { IKContext, IKUpload } from 'imagekitio-vue'

export default {
  name: 'ScratchPage',
  components: {
    // IKImage,
    IKContext,
    IKUpload
  },
  data() {
    return {
      urlEndpoint: 'https://ik.imagekit.io/omnsxzubg0',
      publicKey: 'public_yqzaEpCdyh8yAsDuy9jrBj+bjA8=',
      authenticationEndpoint:
        'https://us-central1-pixstery3-50aa9.cloudfunctions.net/setSignatureImageKit'
    }
  }
}
</script>

```

Can anyone help me troubleshoot this issue? Thank you!

**Comment by imagekitio** [comment]
Initilizaton of SDK is missing

```js
import ImageKit from "imagekitio-vue"
Vue.use(ImageKit, {
  urlEndpoint: "your_url_endpoint",
  // publicKey: "your_public_api_key",
  // authenticationEndpoint: "https://www.your-server.com/auth"
})
```

Please checkout the getting started guide - https://docs.imagekit.io/getting-started/quickstart-guides/vuejs
It has code samples along with a detailed explanation.

**Comment by dosstx** [comment]
I figured out what the problem was and now it has been resolved. The attributes must be hyphenated like so if you are using ESLINT:

https://eslint.vuejs.org/rules/attribute-hyphenation.html

So, I had to change:

```
<IKContext
      :publicKey="publicKey"
      :urlEndpoint="urlEndpoint"
      :authenticationEndpoint="authenticationEndpoint"
    >
```

to:

```
    <IKContext
      :public-key="publicKey"
      :url-endpoint="urlEndpoint"
      :authentication-endpoint="authenticationEndpoint"
    >
```

Works now
