### ISSUE TITLE
Can't build locally?

### ISSUE THREAD

**Issue by Chippd** [imagekit-developer/imagekit-vuejs#44]
I'm getting this error and spent the last 4 hours trying to update dependencies etc until I hit a brick wall. Is there something obvious I'm missing? I'm trying to add a prop to the IKImage which will allow me to pass a function to be called when the image successfully loads
![image](https://user-images.githubusercontent.com/6480754/147301782-59f505e9-eaf8-4332-9cf3-154beac6f6f5.png)

**Comment by imagekitio** [comment]
Seems like a configuration issue in your project.

For a working sample, please refer to the instructions here - https://docs.imagekit.io/getting-started/quickstart-guides/vuejs. This doc also refers to a sample project.

**Comment by ankur-dwivedi** [comment]
Utilize [version 2.0.1](https://www.npmjs.com/package/imagekitio-vue/v/2.0.1), which is compatible with Vue 3 and shouldn't give any issues in the build.
