### ISSUE TITLE
Expose $ResponseMetadata that includes HTTP statusCode and response headers

### ISSUE THREAD

**Issue by imagekitio** [imagekit-developer/imagekit-vuejs#47]

**Comment by ankur-dwivedi** [comment]
Utilize the `onSuccess` functionality available in the `IKUpload` component available in [version 2.0.1](https://www.npmjs.com/package/imagekitio-vue/v/2.0.1). `onSuccess` is called if the upload is successful. The first and only argument is the response JSON from the upload API. The request-id, response headers, and HTTP status code are also accessible using the $ResponseMetadata key that is exposed from the [javascript sdk](https://github.com/imagekit-developer/imagekit-javascript#access-request-id-other-response-headers-and-http-status-code). For detailed information on the `IKUpload` component, please visit the [GitHub repository](https://github.com/imagekit-developer/imagekit-vuejs#file-upload). Below is an example code snippet:

```
<template>
  <IKUpload 
    :onUploadStart="onUploadStart" 
    :onUploadProgress="onUploadProgress"
    :tags="['tag1','tag2']"
    :responseFields="['tags']"
    :onError="onError"
    :onSuccess="onSuccess"
    customCoordinates="10,10,100,100"
  />
</template>

<script>
import { IKUpload } from "imagekitio-vue"

export default {
  name: "app",
  components: {},
  data() {
    return {};
  },
  methods: {
    onError(err) {
      console.log("Error");
      console.log(err);
    },
    onSuccess(res) {
      console.log("Success");
      console.log(res);
    }
    onUploadProgress(evt) {
      console.log("Inprogress ... ", evt);
    };
    onUploadStart(evt) {
      console.log("Upload started");
    },
  }
};
</script>
```
