### ISSUE TITLE
Video support?

### ISSUE THREAD

**Issue by imagekitio** [imagekit-developer/imagekit-vuejs#49]

**Comment by ankur-dwivedi** [comment]
Utilize the `IKVideo` component available in [version 2.0.1](https://www.npmjs.com/package/imagekitio-vue/v/2.0.1). For detailed information on the `IKVideo` component, please visit the [GitHub repository](https://github.com/imagekit-developer/imagekit-vuejs#video-resizing). Below is an example code snippet:

```
<IKContext urlEndpoint="https://ik.imagekit.io/demo/your_imagekit_id">
  <IKVideo  path="/sample-video.mp4"/>
</IKContext>
```
