### ISSUE TITLE
How to know when an upload is in progress?

### ISSUE THREAD

**Issue by imagekitio** [imagekit-developer/imagekit-vuejs#50]

**Comment by ankur-dwivedi** [comment]
Utilize the onUploadProgress and onUploadStart functionalities available in the IKUpload component in [version 2.0.1](https://www.npmjs.com/package/imagekitio-vue/v/2.0.1). For detailed information on the IKUpload component, please visit the [GitHub repository](https://github.com/imagekit-developer/imagekit-vuejs#file-upload). Below is an example code snippet:

`<template>
  <IKUpload 
    :onUploadStart="onUploadStart" 
    :onUploadProgress="onUploadProgress"
    :tags="['tag1','tag2']"
    :responseFields="['tags']"
    :onError="onError"
    :onSuccess="onSuccess"
    customCoordinates="10,10,100,100"
  />
</template>

<script>
import { IKUpload } from "imagekitio-vue"

export default {
  name: "app",
  components: {},
  data() {
    return {};
  },
  methods: {
    onError(err) {
      console.log("Error");
      console.log(err);
    },
    onSuccess(res) {
      console.log("Success");
      console.log(res);
    }
    onUploadProgress(evt) {
      console.log("Inprogress ... ", evt);
    };
    onUploadStart(evt) {
      console.log("Upload started");
    },
  }
};
</script>`
